### ISSUE TITLE
TypeError: src data type = 17 is not supported

### ISSUE THREAD

**Issue by yangyunfei16** [SullyChen/Autopilot-TensorFlow#44]
When I use run_dataset.py to run my model, the error is as follows, how can I solve it?

Predicted steering angle: [[-14.39868]] degrees
Traceback (most recent call last):
  File "run_dataset.py", line 78, in <module>
    new_img=crop_sky(change_bright(full_image))
  File "run_dataset.py", line 25, in change_bright
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
TypeError: src data type = 17 is not supported

**Comment by SullyChen** [comment]
You must convert your image to a different type before passing to cvtColor, as type 17 (signed 8-bit) is not supported by that function.

**Comment by Rudra4321** [comment]
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-90d2e0d67e62> in <module>
     48 #x = np.fromstring(img, dtype='uint8')
     49 #img = cv2.imdecode(img, cv2.IMREAD_UNCHANGED)
---> 50 img = cv2.resize(img, (600,400) )

TypeError: src data type = 17 is not supported
